# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='cooldown_min',
            field=models.IntegerField(default=0),
        ),
    ]
