# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_regulars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 18, 24, 44, 411000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regular',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 18, 25, 5, 112000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
