# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_regulars', '0002_auto_20160707_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
